# -*- coding: utf-8 -*-
"""
装备回收配置文件 - 从CSV生成
"""

# 装备回收配置
RECYCLE_EQUIPMENT = [
    "匕首",
    "井中月",
    "银蛇",
    "无极棍",
    "逍遥扇",
    "裁决之杖",
    "龙纹剑",
    "骨玉权杖",
    "嗜魂法杖",
    "木剑",
    "铁剑",
    "青铜剑",
    "轻型盔甲（男）",
    "轻型盔甲（女）",
    "凝霜",
    "火球术",
    "治愈术",
    "基本剑术",
    "短剑",
    "精神力战法",
    "青铜斧",
    "重盔甲（女）",
    "魔法长袍（女）",
    "灵魂战衣（女）",
    "重盔甲（男）",
    "魔法长袍（男）",
    "灵魂战衣（男）",
    "大火球",
    "攻杀剑术",
    "施毒术",
    "海魂",
    "修罗",
    "凌风",
    "破魂",
    "斩马刀",
    "古铜戒指",
    "青铜头盔",
    "金项链",
    "铁手镯",
    "乌木剑",
    "八荒",
    "水晶魔戒",
    "牛角戒指",
    "蓝色水晶戒指",
    "六绝星环",
    "黑檀项链",
    "黄色水晶项链",
    "黑色水晶项链",
    "魔法头盔",
    "半月",
    "皮制手套",
    "坚固手套",
    "钢手镯",
    "玄铁指环",
    "金戒指",
    "灯笼项链",
    "白色虎齿项链",
    "魅力戒指",
    "道德戒指",
    "白金项链",
    "降妖除魔戒指",
    "躲避手链",
    "偃月",
    "降魔",
    "传统项链",
    "小手镯",
    "银手镯",
    "大手镯",
    "抗拒火环",
    "地狱火",
    "雷电术",
    "疾光电影",
    "灵魂火符",
    "幽灵盾",
    "神圣战甲术",
    "黑色水晶戒指",
    "魔鬼项链",
    "珊瑚戒指",
    "蓝翡翠项链",
    "蛇眼戒指",
    "琥珀项链",
    "刺杀剑术",
    "放大镜",
    "红宝石戒指",
    "珍珠戒指",
    "竹笛",
    "铂金戒指",
    "骷髅戒指",
    "龙之戒指",
    "死神手套",
    "骷髅头盔",
    "魔法手镯",
    "金手镯",
    "道士头盔",
    "尽力手镯",
    "骑士手镯",
    "龙鳞手镯",
    "阎罗手套",
    "力量戒指",
    "泰坦戒指",
    "紫碧螺戒指",
    "圣战戒指",
    "天尊戒指",
    "法神戒指",
    "记忆项链",
    "绿色项链",
    "恶魔铃铛",
    "心灵手镯",
    "三眼手镯",
    "思贝儿手镯",
    "龙之手镯",
    "祈祷头盔",
    "祈祷项链",
    "祈祷手镯",
    "祈祷戒指",
    "凤凰明珠",
    "道士手镯",
    "灵魂项链",
    "黑檀手镯",
    "夏普儿手镯",
    "困魔咒",
    "召唤骷髅",
    "隐身术",
    "集体隐身术",
    "诱惑之光",
    "瞬息移动",
    "火墙",
    "爆裂火焰",
    "地狱雷光",
    "半月弯刀",
    "愤怒之钟（雷）",
    "愤怒之钟（风）",
    "愤怒之钟",
    "生命项链",
    "黑铁头盔",
    "烈火剑法",
    "野蛮冲撞",
    "心灵启示",
    "群体治愈术",
    "召唤神兽",
    "魔法盾",
    "圣言术",
    "冰咆哮",
    "幽灵手套",
    "天珠项链",
    "幽灵项链",
    "莲花宝镜（暗黑）",
    "莲花宝镜（幻影）",
    "莲花宝镜",
    "五色项链（火）",
    "五色项链（冰）",
    "五色项链（雷）",
    "五色项链（风）",
    "五色项链",
    "战神盔甲（男）",
    "战神盔甲（女）",
    "恶魔长袍（男）",
    "恶魔长袍（女）",
    "幽灵战衣（男）",
    "幽灵战衣（女）",
    "斗笠",
    "翔空剑法",
    "莲月剑法",
    "空拳刀法",
    "月魂断玉",
    "冰月神掌",
    "冰月震天",
    "霹雳掌",
    "月魂灵波",
    "雷神戒指",
    "毁灭手镯",
    "神谕项链",
    "昏暗封印",
    "润神戒指",
    "如来手镯",
    "猫眼",
    "怨恨项链",
    "魔幻戒指",
    "天机戒指",
    "巨龙戒指",
    "天鸣戒指",
    "火玉戒指",
    "五彩项链",
    "遗魂项链",
    "荣耀项链",
    "勇士项链",
    "行者帽",
    "战神头盔",
    "虎面头盔",
    "虚空道环",
    "红叶血环",
    "六棱戒",
    "紫金环",
    "武圣之戒",
    "月光石手镯",
    "八面太极戒指",
    "魔灵戒指",
    "石榴戒指",
    "青摇戒指",
    "莲丸戒指",
    "冰沙掌",
    "铁系项链",
    "追魂项链",
    "追风项链",
    "魔令项链",
    "魔令手镯",
    "风掌",
    "气血项链",
    "龙卷风",
    "风震天",
    "击风",
    "流星项链",
    "毁灭魔链",
    "回生术",
    "震天项链",
    "五行神镜",
    "银镜项链",
    "黑皮手套",
    "铁炼腕",
    "英雄手套",
    "强魔震法",
    "月光鞋",
    "无影靴",
    "五彩鞋",
    "猛虎强势",
    "仙云靴",
    "武神之靴",
    "绝地靴",
    "幸运降妖除魔戒指",
    "草鞋",
    "皮靴",
    "赤飞靴子",
    "黑皮靴子",
    "天掌靴子",
    "帝王戒指",
    "武士手镯",
    "火玉手镯",
    "天藤头盔",
]

# 装备回收奖励配置
RECYCLE_REWARDS = {
    "匕首": {"gold": 150, "type": "Weapon"},
    "井中月": {"gold": 14000, "type": "Weapon"},
    "银蛇": {"gold": 5000, "type": "Weapon"},
    "无极棍": {"gold": 10000, "type": "Weapon"},
    "逍遥扇": {"gold": 15000, "type": "Weapon"},
    "裁决之杖": {"gold": 20000, "type": "Weapon"},
    "龙纹剑": {"gold": 25000, "type": "Weapon"},
    "骨玉权杖": {"gold": 30000, "type": "Weapon"},
    "嗜魂法杖": {"gold": 35000, "type": "Weapon"},
    "木剑": {"gold": 25, "type": "Weapon"},
    "铁剑": {"gold": 500, "type": "Weapon"},
    "青铜剑": {"gold": 250, "type": "Weapon"},
    "轻型盔甲（男）": {"gold": 2500, "type": "Armour"},
    "轻型盔甲（女）": {"gold": 2500, "type": "Armour"},
    "凝霜": {"gold": 4000, "type": "Weapon"},
    "火球术": {"gold": 110, "type": "Book"},
    "治愈术": {"gold": 110, "type": "Book"},
    "基本剑术": {"gold": 110, "type": "Book"},
    "短剑": {"gold": 1000, "type": "Weapon"},
    "精神力战法": {"gold": 500, "type": "Book"},
    "青铜斧": {"gold": 1750, "type": "Weapon"},
    "重盔甲（女）": {"gold": 5000, "type": "Armour"},
    "魔法长袍（女）": {"gold": 5000, "type": "Armour"},
    "灵魂战衣（女）": {"gold": 5000, "type": "Armour"},
    "重盔甲（男）": {"gold": 5000, "type": "Armour"},
    "魔法长袍（男）": {"gold": 5000, "type": "Armour"},
    "灵魂战衣（男）": {"gold": 5000, "type": "Armour"},
    "大火球": {"gold": 500, "type": "Book"},
    "攻杀剑术": {"gold": 500, "type": "Book"},
    "施毒术": {"gold": 500, "type": "Book"},
    "海魂": {"gold": 1750, "type": "Weapon"},
    "修罗": {"gold": 3000, "type": "Weapon"},
    "凌风": {"gold": 2250, "type": "Weapon"},
    "破魂": {"gold": 1000, "type": "Weapon"},
    "斩马刀": {"gold": 2500, "type": "Weapon"},
    "古铜戒指": {"gold": 500, "type": "Ring"},
    "青铜头盔": {"gold": 500, "type": "Helmet"},
    "金项链": {"gold": 100, "type": "Necklace"},
    "铁手镯": {"gold": 150, "type": "Bracelet"},
    "乌木剑": {"gold": 500, "type": "Weapon"},
    "八荒": {"gold": 2000, "type": "Weapon"},
    "水晶魔戒": {"gold": 500, "type": "Ring"},
    "牛角戒指": {"gold": 600, "type": "Ring"},
    "蓝色水晶戒指": {"gold": 750, "type": "Ring"},
    "六绝星环": {"gold": 500, "type": "Ring"},
    "黑檀项链": {"gold": 2000, "type": "Necklace"},
    "黄色水晶项链": {"gold": 2000, "type": "Necklace"},
    "黑色水晶项链": {"gold": 2000, "type": "Necklace"},
    "魔法头盔": {"gold": 1500, "type": "Helmet"},
    "半月": {"gold": 1750, "type": "Weapon"},
    "皮制手套": {"gold": 250, "type": "Bracelet"},
    "坚固手套": {"gold": 2500, "type": "Bracelet"},
    "钢手镯": {"gold": 500, "type": "Bracelet"},
    "玄铁指环": {"gold": 1000, "type": "Ring"},
    "金戒指": {"gold": 3500, "type": "Ring"},
    "灯笼项链": {"gold": 2000, "type": "Necklace"},
    "白色虎齿项链": {"gold": 20000, "type": "Necklace"},
    "魅力戒指": {"gold": 3000, "type": "Ring"},
    "道德戒指": {"gold": 3000, "type": "Ring"},
    "白金项链": {"gold": 1500, "type": "Necklace"},
    "降妖除魔戒指": {"gold": 5000, "type": "Ring"},
    "躲避手链": {"gold": 15000, "type": "Necklace"},
    "偃月": {"gold": 2500, "type": "Weapon"},
    "降魔": {"gold": 2500, "type": "Weapon"},
    "传统项链": {"gold": 150, "type": "Necklace"},
    "小手镯": {"gold": 200, "type": "Bracelet"},
    "银手镯": {"gold": 250, "type": "Bracelet"},
    "大手镯": {"gold": 750, "type": "Bracelet"},
    "抗拒火环": {"gold": 500, "type": "Book"},
    "地狱火": {"gold": 500, "type": "Book"},
    "雷电术": {"gold": 500, "type": "Book"},
    "疾光电影": {"gold": 500, "type": "Book"},
    "灵魂火符": {"gold": 500, "type": "Book"},
    "幽灵盾": {"gold": 500, "type": "Book"},
    "神圣战甲术": {"gold": 500, "type": "Book"},
    "黑色水晶戒指": {"gold": 1250, "type": "Ring"},
    "魔鬼项链": {"gold": 2500, "type": "Necklace"},
    "珊瑚戒指": {"gold": 3500, "type": "Ring"},
    "蓝翡翠项链": {"gold": 5000, "type": "Necklace"},
    "蛇眼戒指": {"gold": 1250, "type": "Ring"},
    "琥珀项链": {"gold": 2500, "type": "Necklace"},
    "刺杀剑术": {"gold": 500, "type": "Book"},
    "放大镜": {"gold": 5000, "type": "Necklace"},
    "红宝石戒指": {"gold": 5000, "type": "Ring"},
    "珍珠戒指": {"gold": 1250, "type": "Ring"},
    "竹笛": {"gold": 5000, "type": "Necklace"},
    "铂金戒指": {"gold": 5000, "type": "Ring"},
    "骷髅戒指": {"gold": 3000, "type": "Ring"},
    "龙之戒指": {"gold": 5000, "type": "Ring"},
    "死神手套": {"gold": 5000, "type": "Bracelet"},
    "骷髅头盔": {"gold": 4000, "type": "Helmet"},
    "魔法手镯": {"gold": 1250, "type": "Bracelet"},
    "金手镯": {"gold": 1250, "type": "Bracelet"},
    "道士头盔": {"gold": 4000, "type": "Helmet"},
    "尽力手镯": {"gold": 1250, "type": "Bracelet"},
    "骑士手镯": {"gold": 1000, "type": "Bracelet"},
    "龙鳞手镯": {"gold": 1000, "type": "Bracelet"},
    "阎罗手套": {"gold": 1000, "type": "Bracelet"},
    "力量戒指": {"gold": 1000, "type": "Ring"},
    "泰坦戒指": {"gold": 1000, "type": "Ring"},
    "紫碧螺戒指": {"gold": 1000, "type": "Ring"},
    "圣战戒指": {"gold": 1000, "type": "Ring"},
    "天尊戒指": {"gold": 1000, "type": "Ring"},
    "法神戒指": {"gold": 1000, "type": "Ring"},
    "记忆项链": {"gold": 1000, "type": "Necklace"},
    "绿色项链": {"gold": 1000, "type": "Necklace"},
    "恶魔铃铛": {"gold": 15000, "type": "Necklace"},
    "心灵手镯": {"gold": 1000, "type": "Bracelet"},
    "三眼手镯": {"gold": 1000, "type": "Bracelet"},
    "思贝儿手镯": {"gold": 1000, "type": "Bracelet"},
    "龙之手镯": {"gold": 1000, "type": "Bracelet"},
    "祈祷头盔": {"gold": 1000, "type": "Helmet"},
    "祈祷项链": {"gold": 1000, "type": "Necklace"},
    "祈祷手镯": {"gold": 1000, "type": "Bracelet"},
    "祈祷戒指": {"gold": 1000, "type": "Ring"},
    "凤凰明珠": {"gold": 1000, "type": "Necklace"},
    "道士手镯": {"gold": 1000, "type": "Bracelet"},
    "灵魂项链": {"gold": 1000, "type": "Necklace"},
    "黑檀手镯": {"gold": 1000, "type": "Bracelet"},
    "夏普儿手镯": {"gold": 1000, "type": "Bracelet"},
    "困魔咒": {"gold": 500, "type": "Book"},
    "召唤骷髅": {"gold": 500, "type": "Book"},
    "隐身术": {"gold": 500, "type": "Book"},
    "集体隐身术": {"gold": 500, "type": "Book"},
    "诱惑之光": {"gold": 500, "type": "Book"},
    "瞬息移动": {"gold": 500, "type": "Book"},
    "火墙": {"gold": 500, "type": "Book"},
    "爆裂火焰": {"gold": 500, "type": "Book"},
    "地狱雷光": {"gold": 500, "type": "Book"},
    "半月弯刀": {"gold": 500, "type": "Book"},
    "愤怒之钟（雷）": {"gold": 7500, "type": "Necklace"},
    "愤怒之钟（风）": {"gold": 7500, "type": "Necklace"},
    "愤怒之钟": {"gold": 7500, "type": "Necklace"},
    "生命项链": {"gold": 10000, "type": "Necklace"},
    "黑铁头盔": {"gold": 16500, "type": "Helmet"},
    "烈火剑法": {"gold": 500, "type": "Book"},
    "野蛮冲撞": {"gold": 500, "type": "Book"},
    "心灵启示": {"gold": 500, "type": "Book"},
    "群体治愈术": {"gold": 500, "type": "Book"},
    "召唤神兽": {"gold": 500, "type": "Book"},
    "魔法盾": {"gold": 500, "type": "Book"},
    "圣言术": {"gold": 500, "type": "Book"},
    "冰咆哮": {"gold": 500, "type": "Book"},
    "幽灵手套": {"gold": 7500, "type": "Bracelet"},
    "天珠项链": {"gold": 10000, "type": "Necklace"},
    "幽灵项链": {"gold": 10000, "type": "Necklace"},
    "莲花宝镜（暗黑）": {"gold": 7500, "type": "Necklace"},
    "莲花宝镜（幻影）": {"gold": 7500, "type": "Necklace"},
    "莲花宝镜": {"gold": 7500, "type": "Necklace"},
    "五色项链（火）": {"gold": 4500, "type": "Necklace"},
    "五色项链（冰）": {"gold": 4500, "type": "Necklace"},
    "五色项链（雷）": {"gold": 4500, "type": "Necklace"},
    "五色项链（风）": {"gold": 4500, "type": "Necklace"},
    "五色项链": {"gold": 4500, "type": "Necklace"},
    "战神盔甲（男）": {"gold": 15000, "type": "Armour"},
    "战神盔甲（女）": {"gold": 15000, "type": "Armour"},
    "恶魔长袍（男）": {"gold": 15000, "type": "Armour"},
    "恶魔长袍（女）": {"gold": 15000, "type": "Armour"},
    "幽灵战衣（男）": {"gold": 15000, "type": "Armour"},
    "幽灵战衣（女）": {"gold": 15000, "type": "Armour"},
    "斗笠": {"gold": 4000, "type": "Helmet"},
    "翔空剑法": {"gold": 500, "type": "Book"},
    "莲月剑法": {"gold": 500, "type": "Book"},
    "空拳刀法": {"gold": 500, "type": "Book"},
    "月魂断玉": {"gold": 500, "type": "Book"},
    "冰月神掌": {"gold": 500, "type": "Book"},
    "冰月震天": {"gold": 500, "type": "Book"},
    "霹雳掌": {"gold": 500, "type": "Book"},
    "月魂灵波": {"gold": 500, "type": "Book"},
    "雷神戒指": {"gold": 15000, "type": "Ring"},
    "毁灭手镯": {"gold": 25000, "type": "Bracelet"},
    "神谕项链": {"gold": 15000, "type": "Necklace"},
    "昏暗封印": {"gold": 16500, "type": "Ring"},
    "润神戒指": {"gold": 15000, "type": "Ring"},
    "如来手镯": {"gold": 25000, "type": "Bracelet"},
    "猫眼": {"gold": 15000, "type": "Necklace"},
    "怨恨项链": {"gold": 16500, "type": "Necklace"},
    "魔幻戒指": {"gold": 15000, "type": "Ring"},
    "天机戒指": {"gold": 25000, "type": "Ring"},
    "巨龙戒指": {"gold": 4000, "type": "Ring"},
    "天鸣戒指": {"gold": 4000, "type": "Ring"},
    "火玉戒指": {"gold": 4000, "type": "Ring"},
    "五彩项链": {"gold": 12500, "type": "Necklace"},
    "遗魂项链": {"gold": 12500, "type": "Necklace"},
    "荣耀项链": {"gold": 7500, "type": "Necklace"},
    "勇士项链": {"gold": 12500, "type": "Necklace"},
    "行者帽": {"gold": 7500, "type": "Helmet"},
    "战神头盔": {"gold": 25000, "type": "Helmet"},
    "虎面头盔": {"gold": 25000, "type": "Helmet"},
    "虚空道环": {"gold": 20000, "type": "Ring"},
    "红叶血环": {"gold": 4500, "type": "Ring"},
    "六棱戒": {"gold": 20000, "type": "Ring"},
    "紫金环": {"gold": 20000, "type": "Ring"},
    "武圣之戒": {"gold": 25000, "type": "Ring"},
    "月光石手镯": {"gold": 50, "type": "Bracelet"},
    "八面太极戒指": {"gold": 50, "type": "Ring"},
    "魔灵戒指": {"gold": 17500, "type": "Ring"},
    "石榴戒指": {"gold": 17500, "type": "Ring"},
    "青摇戒指": {"gold": 15000, "type": "Ring"},
    "莲丸戒指": {"gold": 17500, "type": "Ring"},
    "冰沙掌": {"gold": 500, "type": "Book"},
    "铁系项链": {"gold": 17500, "type": "Necklace"},
    "追魂项链": {"gold": 15000, "type": "Necklace"},
    "追风项链": {"gold": 15000, "type": "Necklace"},
    "魔令项链": {"gold": 10000, "type": "Necklace"},
    "魔令手镯": {"gold": 17500, "type": "Bracelet"},
    "风掌": {"gold": 500, "type": "Book"},
    "气血项链": {"gold": 17500, "type": "Necklace"},
    "龙卷风": {"gold": 500, "type": "Book"},
    "风震天": {"gold": 500, "type": "Book"},
    "击风": {"gold": 500, "type": "Book"},
    "流星项链": {"gold": 20000, "type": "Necklace"},
    "毁灭魔链": {"gold": 25000, "type": "Necklace"},
    "回生术": {"gold": 500, "type": "Book"},
    "震天项链": {"gold": 11500, "type": "Necklace"},
    "五行神镜": {"gold": 25000, "type": "Necklace"},
    "银镜项链": {"gold": 11500, "type": "Necklace"},
    "黑皮手套": {"gold": 10000, "type": "Bracelet"},
    "铁炼腕": {"gold": 20000, "type": "Bracelet"},
    "英雄手套": {"gold": 25000, "type": "Bracelet"},
    "强魔震法": {"gold": 500, "type": "Book"},
    "月光鞋": {"gold": 17500, "type": "Shoes"},
    "无影靴": {"gold": 22500, "type": "Shoes"},
    "五彩鞋": {"gold": 4000, "type": "Shoes"},
    "猛虎强势": {"gold": 500, "type": "Book"},
    "仙云靴": {"gold": 20000, "type": "Shoes"},
    "武神之靴": {"gold": 25000, "type": "Shoes"},
    "绝地靴": {"gold": 17500, "type": "Shoes"},
    "幸运降妖除魔戒指": {"gold": 10000, "type": "Ring"},
    "草鞋": {"gold": 500, "type": "Shoes"},
    "皮靴": {"gold": 2500, "type": "Shoes"},
    "赤飞靴子": {"gold": 5000, "type": "Shoes"},
    "黑皮靴子": {"gold": 16500, "type": "Shoes"},
    "天掌靴子": {"gold": 10000, "type": "Shoes"},
    "帝王戒指": {"gold": 15000, "type": "Ring"},
    "武士手镯": {"gold": 1000, "type": "Bracelet"},
    "火玉手镯": {"gold": 25000, "type": "Bracelet"},
    "天藤头盔": {"gold": 4500, "type": "Helmet"},
}
